services:
  controller:
    build: ./controller
    ports:
      - "8000:8000"
    networks:
      onion_net:
        ipv4_address: 10.0.2.254
    
  prometheus:
    image: prom/prometheus
    privileged: true
    user: root
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9090:9090"
    networks:
      onion_net:
        ipv4_address: 10.0.2.253
  
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      onion_net:
        ipv4_address: 10.0.2.252


  # Connection between the client and onion networks
  client:
    build: ./client
    depends_on:
      - controller
    networks:
      client_net:
        ipv4_address: 10.0.1.254
      onion_net:

  clients:
    build: ./client
    depends_on:
      - client
    deploy:
      replicas: 2
    networks:
      - client_net
  
  # Connection between the onion network and the internet
  onion:
    build: ./onion
    privileged: true
    depends_on:
      - controller
    networks:
      onion_net:
        ipv4_address: 10.0.2.251
      
  onions:
    build: ./onion
    privileged: true
    depends_on:
      - onion
    deploy:
      replicas: 3
    networks:
      - onion_net

networks:
  client_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24

  onion_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24

volumes:
  grafana-data:
    driver: local
