scrape_configs:
  - job_name: 'onion-nodes'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: '.*onion.*'
        action: keep
      - source_labels: [__address__]
        target_label: __address__
        regex: '(.*):.*'
        replacement: '${1}:9100'
